# File di configurazione di Netlify per la Scuola di Tailwind (Academy)

[build]
  # Il comando per compilare l'applicazione React + Vite
  command = "npm run build"
  
  # La cartella che contiene la build statica da distribuire su CDN
  publish = "dist"

# Regola di reindirizzamento per le funzioni Serverless (es. Tutor AI)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Regola di reindirizzamento per Single Page Application (SPA)
# Permette a React di gestire le rotte e previene spiacevoli errori 404 all'aggiornamento della pagina.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
