/**
 * Types and interfaces for the Tailwind Playground & Learning Academy
 */

export interface Challenge {
  id: number;
  title: string;
  difficulty: "Facile" | "Medio" | "Difficile";
  category: "Spaziatura" | "Colori" | "Flexbox" | "Grid" | "Stati & Hover" | "Responsive" | "Effetti";
  description: string;
  targetMockupDesc: string; // Detailed description of design goals
  startingCode: string;
  hints: string[];
  // Test rules to check if the user completed the challenge successfully
  validators: {
    requiredClasses: string[]; // Classes that must exist (or patterns)
    forbiddenClasses?: string[]; // Classes that should not be used
    customValidator?: (code: string) => boolean; // Optional code check
  };
}

export interface ComponentItem {
  id: string;
  name: string;
  category: string;
  description: string;
  code: string;
  previewClass?: string; // Optional custom wrapper style
}

export interface ComponentCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp: Date;
  codeSnippet?: string; // Optional code generated by AI
}

export interface CheatSheetItem {
  name: string;
  classes: string[];
  description: string;
  example: string;
}

export interface CheatSheetGroup {
  name: string;
  items: CheatSheetItem[];
}
